<a href="https://colab.research.google.com/github/kavya172/Git-Learning/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


Introduction To Tensors


In [7]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [8]:
scalar.ndim

0

In [10]:
#Get tensor back as python int
scalar.item()

7

In [11]:
#Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [12]:
vector.ndim

1

In [14]:
vector.shape

torch.Size([2])

In [16]:
#MATRIX
MATRIX = torch.tensor([[7,8],[8,9]])
MATRIX

tensor([[7, 8],
        [8, 9]])

In [17]:
MATRIX.ndim

2

In [18]:
MATRIX[1]

tensor([8, 9])

In [19]:
MATRIX.shape


torch.Size([2, 2])

In [21]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],[3,4,5],[2,3,9]]])

In [22]:
TENSOR

tensor([[[1, 2, 3],
         [3, 4, 5],
         [2, 3, 9]]])

In [23]:
TENSOR.ndim


3

In [24]:
TENSOR.shape


torch.Size([1, 3, 3])

In [25]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 4, 5],
        [2, 3, 9]])